### ISSUE TITLE
it's too easy to permanently delete a job

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#18]
A job can be deleted just by clicking on the little checkbox. There is no confirmation box and it's ready to lose some information.

Could we use a 'deleted' status instead to hide those jobs instead of just pruning them out of the DB? This way we will be able to recover them later.

**Comment by Spredzy** [comment]
@goneri  -1 for the deleted status. I mean when I delete something I don't want it to be in deleted status I simply want it to be deleted.

However if it is too easy to delete a job we could add a confirmation window "Are you sure you want to delete this job"

**Comment by goneri** [comment]
@Spredzy, the use of a deleted status can be useful to recover an user mistake. Much like a "recycle bin". We can then do weekly clean up of those 'deleted' jobs with a maintance script. By doing so, we avoid the need for a confirmation box.

For the record, at this point, we don't fully purge a job when we delete it, files remain on the file system.

**Comment by Spredzy** [comment]
@Goneri I still disagree with the idea of the deleted status as I think it adds complexity for something we do not really need.

Ok assuming we create the 'deleted' status, this is what happens : 
- Create a new possible job status
- Do not show the job in the job-list when job status is 'deleted' (user do not want to see deleted stuff)
- Create a new entry on the left side where user can access their 'recycle bin' and be able to restore a job to the state they want ('failure', 'success', whatever....)
- Create a new pruner program that needs to be run weekly or on the basis we want.

All that works simply because a user could possibly make a double mistake in clicking twice (the delete and the confirm button) an action s/he doesn't want to do. Again I disagree, if the user wants to remove something then it is removed. (And we need to fully purge the delete. This is an actual task we have to do).

@ylamgarchal @Prophidys @IxDay What do you guys think, it would be good to have that one 'pre-groomed' before the actual grooming.

**Comment by ylamgarchal** [comment]
Bizzarely, i agree with both of you.

Currently, only the admin of a team can delete a job. We can leverage this feature, the user will use a standart user account and if he wants to delete a job he must login as an admin user of his team or ask an admin user to delete jobs.

But if the admin made a mistake then the job is definitely lost...

Also, if we track the last activity of a remote CI by using the last job id it proceed then potentially we lost such information if we delete the job from the DB.

@Spredzy: we can add a "deleted" field on the database and adapt the controller to only send the not-deleted ones. If the user wants to see the deleted one, we can add an argument on the uri  ?deleted=True.  I agree it demands more work for that but didn't chocked me.

**Comment by Spredzy** [comment]
Well, here clearly there are two discinct operations:
- archive
- delete

delete is what it is, it will delete a job with no recovery possible, because the user stated he wanted to delete the job, then be it. It is a valid operation.

archive would get closer to what you seem to mention. But then we should not auto-purge it, only admin-team could delete an archive not us automatically. It will require effectively more development, not undoable, but I am seriously wondering if that is necessary at that point.

**Comment by cedlecomte** [comment]
@Spredzy +2

**Comment by goneri** [comment]
+2 for what?

**Comment by goneri** [comment]
My preliminary conclusion at this stage in the discussion is that we cannot use the jobstates to reliably identify the last job that has been process by a remote ci: http://softwarefactory-project.io/r/#/c/4336/

**Comment by cedlecomte** [comment]
It's more a story (adding a feature) than an issue. I'm closing it, if you really need this open a card in the trello.

**Comment by goneri** [comment]
The story was in the Trello since the beginning.
